export interface VideoThumbnail {
  quality: string;
  url: string;
  width?: number;
  height?: number;
}

export interface FormatStream {
  url: string;
  itag?: string;
  type?: string;
  quality?: string;
  container?: string;
  encoding?: string;
  qualityLabel?: string;
  resolution?: string;
  size?: string;
}

export interface VideoItem {
  type?: 'video';
  title: string;
  videoId: string;
  author: string;
  authorId: string;
  authorUrl?: string;
  authorThumbnails?: VideoThumbnail[];
  videoThumbnails: VideoThumbnail[];
  description?: string;
  descriptionHtml?: string;
  viewCount: number;
  published: number;
  publishedText: string;
  lengthSeconds: number;
  liveNow?: boolean;
  paid?: boolean;
  premium?: boolean;
  isUpcoming?: boolean;
}

export interface VideoDetail extends VideoItem {
  likeCount?: number;
  dislikeCount?: number;
  genre?: string;
  subtitles?: Array<{ label: string; lang: string; url: string }>;
  recommendedVideos?: VideoItem[];
  formatStreams?: FormatStream[];
  adaptiveFormats?: FormatStream[];
  hlsUrl?: string;
  dashUrl?: string;
}

export interface CommentItem {
  author: string;
  authorThumbnails?: VideoThumbnail[];
  authorId: string;
  authorUrl: string;
  isEdited?: boolean;
  isOwner?: boolean;
  content: string;
  contentHtml?: string;
  publishedText: string;
  likeCount: number;
  commentId: string;
  replies?: {
    replyCount: number;
    continuation?: string;
  };
}

export interface ChannelDetail {
  author: string;
  authorId: string;
  authorUrl: string;
  authorThumbnails?: VideoThumbnail[];
  authorBanners?: VideoThumbnail[];
  subCount: number;
  totalViews?: number;
  joined?: number;
  autoGenerated?: boolean;
  isFamilyFriendly?: boolean;
  description?: string;
  descriptionHtml?: string;
  latestVideos?: VideoItem[];
  relatedChannels?: Array<{ author: string; authorId: string; authorThumbnails?: VideoThumbnail[] }>;
}

export interface PlaylistItem {
  type: 'playlist';
  title: string;
  playlistId: string;
  playlistThumbnail?: string;
  author: string;
  authorId: string;
  authorUrl?: string;
  videoCount: number;
  videos?: VideoItem[];
}

export interface ChannelSearchResult {
  type: 'channel';
  author: string;
  authorId: string;
  authorUrl: string;
  authorThumbnails: VideoThumbnail[];
  autoGenerated: boolean;
  subCount: number;
  videoCount: number;
  description: string;
}

export type SearchItem = VideoItem | PlaylistItem | ChannelSearchResult;

export interface UserPreferences {
  theme: 'dark' | 'light' | 'oled';
  playerType: 'embed' | 'html5';
  autoplay: boolean;
  defaultQuality: '1080p' | '720p' | '480p' | '360p' | 'auto';
  thinMode: boolean;
  region: string;
}

export interface WatchHistoryItem {
  video: VideoItem;
  watchedAt: number;
  progressSeconds?: number;
}

export interface CustomPlaylist {
  id: string;
  title: string;
  createdAt: number;
  videos: VideoItem[];
}
